id: PE41C0ECC
initial_creation_type: ocr
source_metadata:
  volumes:
    2f1bad13c86a482d9fa61b5d4842372f:
      base_file: v069.txt
      image_group_id: I1PD95914
      title: དམ་པའི་ཆོས་པདྨ་དཀར་པོའི་འགྲེལ་པ།
      total_pages: 1538
      volume_number: 69
